<a href="https://colab.research.google.com/github/guille2k16/numpy-pandas-exercices/blob/master/Numpy_Excercises_Session_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Numpy Excercises - Session 2

# Sección nueva

### Exercise 1

Reshape `array1` to 7x3 dimensions.

In [ ]:
array1 = np.arange(0, 21)
#array1 =
#test1(array1)
array1.reshape((7,3))
#test1()

### Exercise 2

Reshape `array2` into a 3D array of 3x3x3 dimensions.

In [ ]:
array2 = np.arange(0, 27).reshape(9, 3)
#array2 = 
#test2()
array2.reshape((3,3,3))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

### Exercise 3: Reshape vs Resize

reshape and resize both do the same thin. So, what's the difference?

Follow the instructions and find out.


In [ ]:
# Run this cell without changing the code.
array3 = np.arange(0, 9)

array3.reshape((3, 3))
print(array3)

array3.resize((3, 3))
print(array3)


[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Question: What is the difference between reshape and resize

a = "resize returns a new copy of the array, while reshape changes the original array"
b = "reshape returns a new copy of the array, while resize changes the original array"
c = "both resize and reshape works in the same way with the original array"
#test3()
answer = b
print(answer)

### Exercise 4

Concatenate arrays `a`, `b`, and `c`.

In [ ]:
a = np.arange(0, 3)
b = np.arange(3, 6)
c = np.arange(6, 9)
#array4 = 
#test4(array4)
np.concatenate([a, b, c])

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### Exercise 5

Concatenate arrays `m1` and `m2` vertically.

In [ ]:
m1 = np.array(
    [
      [1, 2, 3, 4],
      [5, 6, 7, 8]
    ]
)

m2 = np.array(
    [
      [9, 10, 11, 12],
      [13, 14, 15, 16]
    ]
)
#array5 = 
#test5(array5)
np.vstack([m1, m2])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### Exercise 6

Concatenate arrays `m1` and `m2` horizontally.

In [ ]:
m1 = np.array(
    [
      [1, 2, 3, 4],
      [5, 6, 7, 8]
    ]
)

m2 = np.array(
    [
      [9, 10, 11, 12],
      [13, 14, 15, 16]
    ]
)

#array6 = 
#test6(array7)
np.hstack([m1, m2])

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

### Exercise 7

Get all the cells with value equals to `0` as a list of tuples.


In [ ]:
matrix = np.array([
    [1, 4, 7, 5, 0],
    [0, 2, 9, 0, 1],
    [3, 6, 0, 5, 3],
    [7, 3, 0, 1, 0],
    [3, 6, 1, 0, 4]])
#array7 = 
#test5(array7)

xx = np.where(matrix == 0)

%time l1 = [x for x in zip(xx[0],xx[1])]
print(l1)
%time l2 = [tuple(x) for x in np.array(xx).T]
print(l2)



CPU times: user 0 ns, sys: 31 µs, total: 31 µs
Wall time: 35 µs
[(0, 4), (1, 0), (1, 3), (2, 2), (3, 2), (3, 4), (4, 3)]
CPU times: user 0 ns, sys: 79 µs, total: 79 µs
Wall time: 56.5 µs
[(0, 4), (1, 0), (1, 3), (2, 2), (3, 2), (3, 4), (4, 3)]


### Exercise 8

Check the documentation for `np.diag` and `np.fliplr`. Use them to extract the diagonals arrays for `matrix`.



In [ ]:
diag1 = np.diag(matrix)
print(diag1)
diag2 = np.diag(np.fliplr(matrix))
print(diag2)
#testDiag1(diag1)
#testDiag2(diag2)

[1 2 0 1 4]
[0 0 0 3 3]


### Exercise 9

Get the values of the 3th column in `matrix` and the values for the 2th row in `matrix`. Both as numpy arrays.


In [ ]:
column = matrix[:,2]
print(column)
row = matrix[1,:]
print(row)
#testColumn(column)
#testRow(row)

[7 9 0 0 1]
[0 2 9 0 1]


## Exercise 10

Create a new matrix ***x*** from ***a*** and ***m*** with the folowing structure:



```
array([[4, 4, 5, 4, 4],
       [4, 4, 5, 4, 4],
       [4, 4, 5, 4, 4]])
```



In [ ]:
a = np.full((3, 1), 5)
# print(a)
m = np.full((3, 4), 4)
# print(m)
np.insert(m, 2, a.flatten(), axis=1)


array([[4, 4, 5, 4, 4],
       [4, 4, 5, 4, 4],
       [4, 4, 5, 4, 4]])

## Exercise 11

Given a:

```
a = array([[1],
       [1],
       [2],
       [4]])
```

Create a new array **b** with the following structure:

```
np.array([
  [1, 0, 0],
  [1, 0, 0],
  [0, 1, 0],
  [0, 0, 1],
])
```
Do you detect the pattern? Which operation do you need to create this structure.?




In [259]:
# one hot encode excersise for numpy 
import numpy as np
a = np.array([[1],
       [1],
       [2],
       [4]])

def fc(x):
    return list(map(int, "{0:b}".format(x).zfill(3)))
vfc = np.vectorize(fc, otypes=[list])
tt = vfc(a[::-1].flatten())
b = np.stack(tt)
print(b)


[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]]


# Challenge, Tic Tac Toe


In [ ]:
import numpy as np

cell = {
    0: ' ',
    1: 'X',
    2: 'O'
}

def print_board():
  print('-------------')
  print(f'| {cell[game[0][0]]} | {cell[game[0][1]]} | {cell[game[0][2]]} |')
  print('-------------')
  print(f'| {cell[game[1][0]]} | {cell[game[1][1]]} | {cell[game[1][2]]} |')
  print('-------------')
  print(f'| {cell[game[2][0]]} | {cell[game[2][1]]} | {cell[game[2][2]]} |')
  print('-------------')

def skynet_move():
  # Select a random empty cell in `game` array and set with value `2`.
  # If no empty cells available, do nothing.
  coords = [tuple(x) for x in np.array(np.where(game == 0)).T]
  coords_len = len(coords)
  if coords_len > 0:
    coord = coords[np.random.randint(0, coords_len)]
    game[coord] = 2

def win_move(player, r, c):
  # Check if the player's move is a win move.
  # A win move meets one of these conditions:
  #   - All values at row `r` are equal to `player`.
  #   - All values at column `c` are equal to `player`.
  #   - All values at main diagonal ((0, 0) to (2, 2)) are equal to  `player`.
  #   - All values at second diagonal ((2, 0) to (0, 2)) are equal to  `player`.þ
  # Return True if one of the conditions are met, False otherwise.
  if np.all(game[r,:] == player) or np.all(game[:,c] == player) or np.all(np.diag(game) == player) or np.all(np.diag(np.fliplr(game)) == player):
    return True

  return False

def human_move(r, c):
  # Set value `1` at game[r][c] if the cell if empty and return True.
  # If cell is not empty print "Cell is not empty" and return False.
  if game[r, c] == 0:
    game[r, c] = 1
    return True
  else:
    print('Cell is not empty')
    return False

def winner_exists():
  # If one of the players has already won the game, return True.
  # Return False otherwise.
  win_exist = False
  for player in range(1,3):
    for pos in range(0,3):
      win_exist |= np.all(game[:,pos] == player)
      win_exist |= np.all(game[pos,:] == player)
  
  return win_exist


def is_game_on():
  # This method checks the current status of the game.
  # A game is on if meets one of two conditios:
  #  - There is still available cells.
  #  - There is still no winners. 
  if not winner_exists() and np.where(game == 0)[0].size > 0:
    return True
  else:
    return False

In [ ]:
# Run this cell to restart the game.

# Create a 3x3 array with zero values.
game = np.zeros((3,3), int)

In [ ]:
#@title Tic tac toe controls
#@markdown Select the cell for your next move!.
row_value = "0" #@param ["0", "1", "2", ""]
column_value = "2" #@param ["0", "1", "2", ""]

if row_value != "" and column_value != "":
  row = int(row_value)
  column = int(column_value)
  if(is_game_on()):
    status = human_move(row, column)
    if(win_move(1, row, column)):
      print('Human wins')
    elif(status):
      skynet_move()
      if(win_move(2, row, column)):
        print('Skynet wins')
  else:
    print('Game over.')
else:
  print('Please select your next move.')

print_board()

Game over.
-------------
| X |   | X |
-------------
| O | O | O |
-------------
| X | O | X |
-------------


# Challenge: Basic data analysis

The following numpy array is taken from the a census dataset. Every column in this matrix contains some demografic information. For this exercise You will focus in the following columns:

*   Column[0]: Age
*   Column[1]: workclass
*   Column[3]: education
*   Column[5]: marital-status
*   Column[9]: sex
*   Column[10]: capital-gain

Please find the following information:


*   Age average
*   Types of workclass, education and marital-status
*   How many records are for male
*   How many records are for female
*   How many females are above age of 30
*   Avergage of capital-gain for males
*   Avergage of capital-gain for females







In [116]:
# First upload file "census.npy" befor running this cell.
with open('census.npy', 'rb') as f:
  census_data = np.load(f, allow_pickle=True)
#census_data

array([[50, ' Self-emp-not-inc', 83311, ..., 13, ' United-States',
        ' <=50K'],
       [38, ' Private', 215646, ..., 40, ' United-States', ' <=50K'],
       [53, ' Private', 234721, ..., 40, ' United-States', ' <=50K'],
       ...,
       [58, ' Private', 151910, ..., 40, ' United-States', ' <=50K'],
       [22, ' Private', 201490, ..., 20, ' United-States', ' <=50K'],
       [52, ' Self-emp-inc', 287927, ..., 40, ' United-States', ' >50K']],
      dtype=object)

In [173]:
print('Age average: ', census_data[:,0].mean())

Age average:  38.581633906633904


In [151]:
print('Type of workclass:')
print(np.unique(census_data[:,1]))
print('Type of education:')
print(np.unique(census_data[:,3]))
print('Type of marital-status:')
print(np.unique(census_data[:,5]))  

Type of workclass:
[' ?' ' Federal-gov' ' Local-gov' ' Never-worked' ' Private'
 ' Self-emp-inc' ' Self-emp-not-inc' ' State-gov' ' Without-pay']
Type of education:
[' 10th' ' 11th' ' 12th' ' 1st-4th' ' 5th-6th' ' 7th-8th' ' 9th'
 ' Assoc-acdm' ' Assoc-voc' ' Bachelors' ' Doctorate' ' HS-grad'
 ' Masters' ' Preschool' ' Prof-school' ' Some-college']
Type of marital-status:
[' Divorced' ' Married-AF-spouse' ' Married-civ-spouse'
 ' Married-spouse-absent' ' Never-married' ' Separated' ' Widowed']


In [204]:
sex=census_data[:,9]
print('Females count: ', np.count_nonzero(sex ==' Female'))
print('Males count: ', np.count_nonzero(sex ==' Male'))

Females count:  10771
Males count:  21789


In [205]:
females_gt_30 = np.count_nonzero((census_data[:,9] == ' Female') & (census_data[:,0] > 30))
print('Females count greater than 30: ', females_gt_30)

# a = census_data[(census_data[:,9] == ' Female') & (census_data[:,0] > 30)]
# len(a[:, (0,9)])

Females count greater than 30:  6512


In [246]:
print('Avergage of capital-gain for males: ', census_data[(census_data[:,9] == ' Male')][:,10].mean())
print('Avergage of capital-gain for females: ', census_data[(census_data[:,9] == ' Female')][:,10].mean())

Avergage of capital-gain for males:  1329.3313139657625
Avergage of capital-gain for females:  568.4105468387336
